### ISSUE TITLE
Why the sane@3.1.0 don't support node 9.*.*

### ISSUE THREAD

**Issue by howel52** [sane/sane#211]
I was install sane@3.1.10 in window 10 and node 9.10.1

Got a error message: 
> sane@3.1.0: The engine "node" is incompatible with this module. Expected version "6.* || 8.* || >= 10.*". Got "9.10.1"

**Comment by jelhan** [comment]
NPM package `sane` refers to another project: https://github.com/amasad/sane This one provides `sane-cli` package and has nothing to do with `sane` npm package.

**Comment by howel52** [comment]
Thanks 😊
