### ISSUE TITLE
imagescan -L does not look for scanners in Docker properly

### ISSUE THREAD

**Issue by alex-mashin** [sane/sane#213]
I have an Epson scanner, currently at `/dev/bus/usb/001/004`. A `udev` rule symlinks it to `/dev/epson_scanner`.

In a Docker container base on `debian:stable-slim`, `sane-find-scanner` and `scanimage -L` discovers the scanner, only if the device is mapped the the same name as in the host:

These fail:
```yaml
    devices:
      - "/dev/epson_scanner:/dev/usb/scanner0"
      - "/dev/epson_scanner:/dev/bus/usb/001/005"
      - "/dev/bus/usb/001/004:/dev/usb/scanner0"
```

These succeed:
```yaml
    devices:
      - "/dev/epson_scanner:/dev/bus/usb/001/004"
      - "/dev/bus/usb/001/004:/dev/bus/usb/001/004"
```

I expect that symlink devices will be recognised by `scanimage -L` even in Docker, which has been able to deal with them for several years.

**Comment by IanVS** [comment]
This is the wrong repo.  This is a web development stack.  You're looking for something else.

**Comment by alex-mashin** [comment]
> This is the wrong repo. This is a web development stack. You're looking for something else.

Sorry, moved there: https://gitlab.com/sane-project/backends/-/issues/756.
